# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmodel',
            name='image',
            field=models.ImageField(upload_to='images/pics'),
        ),
    ]
