# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-18 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_feedbackmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='image',
        ),
    ]
